### ISSUE TITLE
Awesome List Section proprietary

### ISSUE THREAD

**Issue by DavidLambauer** [Magenerds/PageDesigner#1]
Hi there,

as you noticed on twitter, I added this module to the [Magento 2 Awesome List](https://github.com/DavidLambauer/awesome-magento2). Due to that, I just saw that the license you entered in your Composer.json says proprietary. 

Would you like to stay with that, or do plan to make it open source? Either way, I'll put the module to the proprietary section of the awesome list for now. 

Greetings,

David

**Comment by sydekumf** [comment]
Thanks for reminding us :-) It is open source now :-)

**Comment by DavidLambauer** [comment]
Thanks,

it's absolutely legit to use the proprietary license, by the way. What about the [Base Price](https://github.com/Magenerds/BasePrice/blob/master/composer.json) ?

**Comment by sydekumf** [comment]
BasePrice fixed also :D
I am not sure. We would appreciate the participation in the development by the community, so shouldn't it be open source then?
Also the doc block inside the source files also says OSL 3.0, so it should be fine :-)

**Comment by DavidLambauer** [comment]
Great!! Thank you for that.
