### ISSUE TITLE
JS issues with the plus icon

### ISSUE THREAD

**Issue by gewaechshaus** [Magenerds/PageDesigner#10]
Hey Nerds,

I am still facing the issue that I can't click on the plus icon to add content... I disabled merge, minify and grouping of all js files to track the issue.

It seems like  ".mceButton.mce_magentowidget" is undefined in my case. I enabled some logging 

         console.log(JSON.parse(JSON.stringify(wysControl.find('.mceButton.mce_magentowidget'))));

as you can see in https://dev.makerdise.com/static/adminhtml/Magento/backend/en_US/Magenerds_PageDesigner/js/page_designer.js

![Screenshot](https://pictr.com/images/2017/05/19/HbMTn.png)

TinyMCE seems to get included fine.

**Comment by sippsolutions** [comment]
I'll close this issue due to its age. If this is still an issue, feel free to open a new one.
