### ISSUE TITLE
Problem with content in frontend

### ISSUE THREAD

**Issue by MathieuJJ** [Magenerds/PageDesigner#11]
Hi,
Fiestly, thank you for your module!

In admin, the module perfectly works but the generated content is boken. For a page with only one row and one column with a Wysiwyg Block, the content in ffontend is :

Pj4 QkFTRTY0Pj4 VUVoQksxQkhiSFJhZVVKNlkyMU5PVWx1ZERkaVYxWnJZVmRGWjJSWVNuTlFVMG96WlZoT2NHUXpiRzVNTW5BeFlrZEtka3d5WkhsYVYxWjFZa2RHZFZwRE9XNWpiVlpzWW0xNGFHSnRVWFJOYVRWeFkwZGphV1pZTUdsSlIwWnpaRVF3YVdGdVZuTlpiVGhwU1Voa2NGcElVbTlRVTBrMVRtcEJhVWxIYUd4aFYyUnZaRVF3YVU1cVZUTkphVUYyVUdwM2RtTkVORDA9

Any idea ?

Thank you advance,
Mathieu

**Comment by MathieuJJ** [comment]
And when I edit the wysiwyg content in admin, the content (simple image for example) is not restored : <p>Pj4+QkFTRTY0Pj4+VUVoQksxQkhiSFJhZVVKNlkyMU5PVWx1ZERkaVYxWnJZVmRGWjJSWVNuTlFVMG96WlZoT2NHUXpiRzVNTW5BeFlrZEtka3d5WkhsYVYxWjFZa2RHZFZwRE9XNWpiVlpzWW0xNGFHSnRVWFJOYVRWeFkwZGphV1pZTUdsSlNHUndXa2hTYjFCVFNUVk9ha0ZwU1Vkb2JHRlhaRzlrUkRCcFRtcFZNMGxwUVhaUWFuZDJZMFEwUFE9PQ==</p>

**Comment by sydekumf** [comment]
The content gets encoded in Base64. Are you sure you did not made any mistakes during saving like deleting some character or so? Maybe you retry it?
Which Magento version do you use and which content do you save? Try a simple text?

**Comment by MathieuJJ** [comment]
Hi,
Thank you for your reply!
I am sure I dit not remove any character, the problem is the same with an image or a simple text.  With this example `<p>hello</p>`, in the frontend or when I edit the wysiwyg content, the text is replaced by Pj4+QkFTRTY0Pj4+VUVoQksyRkhWbk5pUnpnNFRETkJLdz09. No JS error and no error in the support or debug log files. The Magento version is 2.1.4. 
Thank you for your help!

**Comment by MathieuJJ** [comment]
Hi,
It was a conflict with on other module (Ves Page Biuilger). That is fixed! Thank you for your help!
Mathieu
