### ISSUE TITLE
Performance problem with large content

### ISSUE THREAD

**Issue by MathieuJJ** [Magenerds/PageDesigner#12]
Hi,
When you add large html content, the browser freeze a few seconds (until 30 seconds on firefox). The problem is in the tinymce init function.
To solve this issue, I removed content on the textarea tag before to call the tinymce init method.
In page_designer.js, I added the line "jQuery('.textarea').val('');" on line 69 juste before init calling.
Mathieu

**Comment by sydekumf** [comment]
Hey thanks for reporting :-) Can you do a pull request for this? :-)

**Comment by MathieuJJ** [comment]
I tried but I have an error: Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository.

**Comment by sydekumf** [comment]
You have to fork it first in your private repository, commit the changes there and then open up a pull request :-)

**Comment by s00071609** [comment]
Has this been resolved or is this problem still there?>
