### ISSUE TITLE
Custom module with textarea

### ISSUE THREAD

**Issue by MathieuJJ** [Magenerds/PageDesigner#14]
Hi,
 Is it complicated to use your module in a custom module with a textarea?
I tried somes changes in di.xml but it does not work.
Than you for your reply.
Mathieu

**Comment by MathieuJJ** [comment]
I built my custom form directly in the block and not in the layout file like CMS module. I tried to override my ccontent field with your module, no result. Do you have any idea? Thank you very much for your help!

**Comment by MathieuJJ** [comment]
Hi, I will be very grateful if you could give somes tips. Than you!

**Comment by sydekumf** [comment]
Hi,

sorry for the late reply :-) What exactly do you want to achieve? What textarea do you want to integrate? And how do you extend our module?

Thanks,
Florian

**Comment by MathieuJJ** [comment]
Hi,
Thank you for your reply!
I would like to transform a simple wysiwyg editor in my custom admin module to a pagedesigner field. I do not know what is the best way. Do you think is it possible?
Mathieu

**Comment by sydekumf** [comment]
In the content section of a CMS page you can insert a wysiwyg editor, even in the page designer :-)

**Comment by MathieuJJ** [comment]
Thank you for your reply, I will try to reformulate my need.
I created a custom module to administrate custom information needed by my
client. In this custom module, in the form admin, there is a field with a
wysiwyg editor.
Instead of this classic editor, I would like to use your pagedesigner
editor. How can I do that?
Thank you again for your help!

2017-09-19 14:41 GMT+04:00 Florian Sydekum <notifications@github.com>:

**Comment by sydekumf** [comment]
Mh I think I got your point now :-) Sry if I did not understand it correctly before. Unfortunately there is no easy way to integrate it, as it is not just a form element like a wysiwyg editor. It is much more complex as it replaces logic like saving CMS, rendering logic in the frontend and so on. I am sorry there is no better way.

**Comment by sippsolutions** [comment]
Feel free to use PageDesigner in your module if you want. Unfortunately there is no built-in "ready to use" functionality to integrate into other forms.
