### ISSUE TITLE
Problem with minified wysiwyg css files

### ISSUE THREAD

**Issue by duckchip** [Magenerds/PageDesigner#17]
Magento: 2.1.9

When installing this module, I get problems with the css files of the wysiwyg components. All the wysiwyg css files are minified on the server, although in Magento/Store/etc/config.xml following lines are defined in Magento/Store/etc/config.xml
 <minify_exclude>
/tiny_mce/
</minify_exclude>

Now in your module there's also something with minify_exclude: 
<css>
    <minify_exclude>
    /Magenerds_PageDesigner/css/pd-ui.css
     </minify_exclude>
</css>

Could it be that this rule overwrites the one in Magento/Store?  
I also see that you extend/overwrite some implementation and definitions of the wysiwyg component in PageDesigner/view/adminhtml/web/js/page_designer.js

This problem only occurs on production mode with minifying enabled 
 
Could you try to combine both 'minify_exclude' definitions in your module? 

Thanks in advance!
![screen shot 2017-10-17 at 15 06 27](https://user-images.githubusercontent.com/9752966/31671787-139168fa-b35b-11e7-875e-8b9f5c006acc.png)

**Comment by sydekumf** [comment]
Hi there,

in general Magento merges configuration files, and does not overwrite them: http://devdocs.magento.com/guides/v2.0/config-guide/config/config-files.html#config-files-loadmerge

**Comment by duckchip** [comment]
hmmm Unfortunately our backend wysiwyg attributes aren't styled anymore when installing the PageDesigner module, and we'd really like to try this extension out 👍

**Comment by vivien2k** [comment]
Exactly the same issue here with magento 2.2.2 with css minification...

**Comment by hostep** [comment]
@sydekumf: Indeed, Magento *should* merge these configurations, but alas, it doesn't do this in this case, this feels like yet another Magento bug.
The temporary fix is to change the config.xml file in your module to:
```
                <minify_exclude>
                    /Magenerds_PageDesigner/css/pd-ui.css
                    /tiny_mce/
                </minify_exclude>
```

In this case @duckchip reported issue will be solved, but in my opinion this is only a temporary fix until Magento fixes the merging of this configuration setting.
Let me link to to this bugreport on the Magento2 repo, which kind of deals with this problem: https://github.com/magento/magento2/issues/11577
