### ISSUE TITLE
Plus icon false trigger

### ISSUE THREAD

**Issue by gewaechshaus** [Magenerds/PageDesigner#2]
Hey there,

with enabled JS minification, (bundling) and merging the module doesn't work as excepted (in production mode). 

I only did a few tests:
- Compared my system to the demo (https://demo-pagedesigner.magenerds.com/admin/cms/page/). It seems like the demo is running in developer mode as by configuration  JS minification and merging are enabled 
- Switched to developer mode, everything is working like in the dev
- No significant errors on the console, will have a look at the logs now

Biggest issue: can't add a new block by clicking the + icon... It looks like this line is always getting triggered
https://github.com/Magenerds/PageDesigner/blob/master/view/adminhtml/web/js/page_designer.js#L182

Issue
- The editor will never 
So maybe someone can verify this before we dig deeper into the code.

Regards
Jan

**Comment by sydekumf** [comment]
Hi Jan,
thanks for reporting! We just comitted a fix for the editor. Does it help?
Are there more issues? You wrote that you can't add blocks via the + icon. Maybe you can separate the problems in separate issues? :-)

**Comment by JSchlarb** [comment]
Hey @sydekumf, please create a release for it :)

**Comment by gewaechshaus** [comment]
@JSchlarb @sydekumf - THX a lot, I will test your fix in the next minutes...

**Comment by gewaechshaus** [comment]
@JSchlarb @sydekumf - That doesn't seem to do the trick, same result as before :( 

Triggered:
https://github.com/Magenerds/PageDesigner/blob/master/view/adminhtml/web/js/page_designer.js#L182


![Image](https://pictr.com/images/2017/03/20/3ec8148eb874dbff1d33ab0a23e44db9.jpg)


Maybe we should test some <exclude> logic so sort the requests.

**Comment by JSchlarb** [comment]
Got it :D. The controls are overlapping.

**Comment by gewaechshaus** [comment]
Lol, to be honest, I didn't thought that simple :) (as always ;)) Screenshots speaks more than words in our world :)

**Comment by JSchlarb** [comment]
Maybe you can confirm it by executing this `jQuery('.pd-col-content-controls').css('display', 'none');`.  Of course this will cause other problems but it will show that I'm on the right way :)

<img width="846" src="https://cloud.githubusercontent.com/assets/715666/24097288/768c40c0-0d65-11e7-9064-0101562eb75e.png">

**Comment by gewaechshaus** [comment]
Looks good... Seems to overlap, could trigger the plus icon like it should this way. 

Another way to verify: If you put in a new row and resize the default element to the smallest possible size, the plus icon does get triggered.

**Comment by gewaechshaus** [comment]
In general I also noticed a visual difference related to the box sizes in our case. They don't stretch to fullsize like in the demo and are kind of unresponsive and limited in sizing. I can put this in another issue to keep things clean.

https://github.com/Magenerds/PageDesigner/issues/4

**Comment by JSchlarb** [comment]
Hi Jan,
This one is also related to [this](https://github.com/magento/magento2/issues/8552) expect the min with. PR #5 should fix the issue with overlapping controls.

**Comment by sydekumf** [comment]
Here is the release :-) https://github.com/Magenerds/PageDesigner/releases/tag/1.0.3
