### ISSUE TITLE
Duplicate plugin name in use

### ISSUE THREAD

**Issue by hostep** [Magenerds/PageDesigner#21]
Not sure how important this is, but I've noticed that the plugin name `Magenerds_PageDesigner::injectPageHtmlIntoJson` is being defined twice in the [`di.xml`](https://github.com/Magenerds/PageDesigner/blob/8c9d94a/etc/di.xml) file. Just thought I should let you know. I'm not exactly sure if you can use the same name twice or not for plugins...

According to [Alan Storm](https://alanstorm.com/magento_2_object_manager_plugin_system/), it should be unique:
> Under type is the `<plugin/>` node. Here, the name should be a unique identifier that distinguishes this plugin configuration from every other plugin configuration in the world. The name is freeform, but you should use some combination of module name and description to make sure the name is unique.

But nothing is mentioned in the [devdocs](http://devdocs.magento.com/guides/v2.2/extension-dev-guide/plugins.html) around this:
> `plugin name`. An arbitrary plugin name that identifies a plugin. Also used to merge the configurations for the plugin.

So I'm not exactly sure if it has to be unique or not ...

Feel free to close when this isn't an issue :)

**Comment by sydekumf** [comment]
Thanks, we fixed that :-)
