### ISSUE TITLE
Not working in magento 2.3.0

### ISSUE THREAD

**Issue by KoenSlagter** [Magenerds/PageDesigner#26]
We've installed magento 2.3.0 and this module isn't working anymore.

We're getting the following error:
[ERROR] Failed to load the "Magenerds_PageDesigner/js/page_designer" component.

Untill know we haven't managed to debug it either,
Has anyone else encoutered this problem? And has been able to resolve it?

Sincerely,
Koen

**Comment by sippsolutions** [comment]
Hi Koen,

currently the Page Designer is not ready for Magento 2.3.
We're working on it and will provide an update soon.

Simon

**Comment by sippsolutions** [comment]
Please have a look at version 4.0.0 released just now.
