### ISSUE TITLE
Uncaught Error: Class 'Zend_Feed_Reader'

### ISSUE THREAD

**Issue by MichielTG** [Magenerds/PageDesigner#28]
When opening the Magenerds dashboard on the left site in developer and production I get:

Fatal error: Uncaught Error: Class 'Zend_Feed_Reader' not found in /var/www/vhosts/......./vendor/magenerds/dashboard/Block/Adminhtml/Dashboard.php:52 Stack trace: #0 

I tested on the latest 4.0.0 version for Magento 2.3

**Comment by MichielTG** [comment]
![image](https://user-images.githubusercontent.com/46106706/52787312-bba8bb80-305d-11e9-96d4-5ed4b091aa6f.png)

**Comment by sydekumf** [comment]
You can run `bin/magento module:disable Magenerds_Dashboard` as it is not necessary to run the modules.
