### ISSUE TITLE
Feature request - integration for category

### ISSUE THREAD

**Issue by SilvanLaroo** [Magenerds/PageDesigner#29]
Hi Megenerds,

Thanks for this awesome extension. It works great, but we have one limitation. We would like to use it for categorypages as well. Would it be possible to integrate this into a categorypage?

Regards,
Silvan

**Comment by sydekumf** [comment]
You can if you build a CMS block and integrate in the category page with display setting "products and cms blocks".

**Comment by vadimjustus** [comment]
Hi @SilvanLaroo
Is this still an issue?
