### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by gewaechshaus** [Magenerds/PageDesigner#31]
Hey, 
Hello @sippsolutions,

we wan't a different sort order for the blocks in our mobile views - is it generaly possible? Before we save the page the order does match our specification, but after saving the view the order is the same in each view.

Greetings
Jan

**Comment by sippsolutions** [comment]
Hi Jan,

unfortunately this is not supported.
You could add classes to your blocks and then add CSS for that class to the mobile breakpoint which then arranges the blocks via [flexbox order](https://developer.mozilla.org/de/docs/Web/CSS/order).

Regards,
Simon

**Comment by gewaechshaus** [comment]
Hi Simon,

ok, many thanks for your fast reply. I already did thought about using flexbox order, but it makes things kind of static/complex(for clients) in terms of the PD flexibility. Maybe this should be implemented in a future release of the PageDesigner. 

Viele Grüße + schönen Feierabend,
Kind regards,
Jan
