### ISSUE TITLE
Catalog Product List widget compatibility

### ISSUE THREAD

**Issue by sarkadiadam** [Magenerds/PageDesigner#33]
Hello,

Whenever I try to add the "Catalog Products List" widget in a row or column I get the this error in my system.log after saving it and trying to re-open it, and of course the widget won't re-open anymore:

main.ERROR: Notice: Array to string conversion in /Volumes/Projects/magento2/m23-demo/vendor/magenerds/wysiwyg-widget/Wysiwyg/Encoder.php on line 83 [] []

It does not happen with the "Catalog New Products List" widget, which makes me think it has some problem decoding the "Conditions" field.

![Screen Shot 2019-04-04 at 15 53 09](https://user-images.githubusercontent.com/49277901/55557704-1de37b80-56f3-11e9-8feb-2c640b59c0b3.png)

Magento version: 2.3.0
Pagebuilder version: 4.0.0

Thanks,
Adam

**Comment by sippsolutions** [comment]
Hey @sarkadiadam,
thanks for the report.
Can you please add this issue to the magenerds/wysiwyg-widget repository?
Thank you!

**Comment by hostep** [comment]
@sippsolutions : it looks like it was already reported about a month ago: https://github.com/Magenerds/WysiwygWidget/issues/1

**Comment by sippsolutions** [comment]
@hostep cool, we will look into that asap

**Comment by sippsolutions** [comment]
@hostep @sarkadiadam this should be fixed in WysiwygWidget 1.0.5. Feel free to update.
