### ISSUE TITLE
Problems with modifying/saving widgets inside a Wysiwyg Editor.

### ISSUE THREAD

**Issue by sarkadiadam** [Magenerds/PageDesigner#37]
Hello,

I've detected a problem in the case of modifying and saving other widgets **inside** the wysiwyg editor field.

![Screen Shot 2019-05-22 at 16 42 52](https://user-images.githubusercontent.com/49277901/58179484-f3547e80-7cb0-11e9-82cd-b53660c6fe20.png)

Ways to reproduce:
1. Create a row->column, add a Wysiwyg Editor inside that column.
2. Inside that Wysiwyg Editor insert a widget (or multiple ones) using the "Insert widget" button.
3. Save the Wysiwyg Editor.
4. Re-open the Wysiwyg Editor and click on a widget inside it to modify it, change some values and click on Save.
5. Save the Wysiwyg Editor.
6. This should lead you to the error in the screenshot above.

PageDesigner version: 4.1.1 (latest dependencies)
Magento version: 2.3.1

Thank You,
Adam

**Comment by patruvlad** [comment]
I can confirm this is an issue, tested on latest Magento version 2.3.1

**Comment by sippsolutions** [comment]
Thanks for reporting. This should be fixed in PD 4.1.3.
