### ISSUE TITLE
Resizing layout elements

### ISSUE THREAD

**Issue by gewaechshaus** [Magenerds/PageDesigner#4]
- Magento 2.1.5 running in production mode, compiled, bundled, minified JS/CSS
- PageDesigner 1.0.2

You can't resize the layout elements bigger than the default size, there's only one smaller size available.

Regards
Jan

**Comment by JSchlarb** [comment]
Please provide more informations or a detailed list of steps that allows us to reproduce your issue.

**Comment by gewaechshaus** [comment]
@JSchlarb - for sure. See the screenshot below...

![Image](https://pictr.com/images/2017/03/21/47d17f3f4af6bda05f7e5ee8d89e5a37.jpg)

1. Enable production mode and JS bundling, combining and merging
2. Go to any cms page with pageDesigner enabled
3. Try to resize one of it's containers

**Comment by JSchlarb** [comment]
This one is related to [this](https://github.com/magento/magento2/issues/8552) :(

**Comment by gewaechshaus** [comment]
Damn, stumbled upon the next core bugs.

**Comment by sydekumf** [comment]
We minify our css with https://github.com/SnowdogApps/magento2-frontools so the bug does not occur for us in production. But of course the core bug has to be fixed.

**Comment by gewaechshaus** [comment]
@sydekumf - Thx... Maybe I will fiddle around with it later, trying to < exclude > the related css from minification as a q&d solution.

**Comment by JSchlarb** [comment]
Hi @gewaechshaus, maybe you can give it a try. pd-ui.css won't minified on 2.1.5 CE & EE. https://github.com/JSchlarb/PageDesigner/commit/f1d6fea1259f63dd5732154b166f993a3616f909

**Comment by gewaechshaus** [comment]
@JSchlarb - this will work I guess... I fiddled around with something similar but didn't find the time to finaly get it working. Will give it a try this way now!

**Comment by gewaechshaus** [comment]
@JSchlarb - works "seamless" as excepted - thumbs up! I didn't set the < dev > node in my config, learned something again 👍 

Also fixed the issue in #2 

@JSchlarb - there's another issue with the plus icon now :)

    wysControl.find(...).get(...) is undefined

Potential collision with 
https://github.com/Magenerds/PageDesigner/blob/master/view/adminhtml/web/js/page_designer.js#L285

**Comment by JSchlarb** [comment]
The collision is correct and expected. But this means that your wysiwyg editor is disabled. Can you check under General» Content Management » WYSIWYG Options » Enable WYSIWYG Editor that it's enabled?

**Comment by gewaechshaus** [comment]
@JSchlarb - no, it was/is enabled... There were some tiny mce related, object chain breaking failures caused by

https://github.com/JSchlarb/PageDesigner/commit/f1d6fea1259f63dd5732154b166f993a3616f909

   
          <js>
                <minify_files>1</minify_files>
                <minify_exclude>
                    /Magenerds_PageDesigner/js/vendor/              
               </minify_exclude>
         </js>

After removing the part from config.xml it looks good and there's no collision with https://github.com/Magenerds/PageDesigner/blob/master/view/adminhtml/web/js/page_designer.js#L285...

**Comment by JSchlarb** [comment]
I'm unable to reproduce this issue. Maybe you can share with me your system config and also installed modules.

I created a new release 1.0.5. https://github.com/Magenerds/PageDesigner/commit/3399aca7b3275493f358a00ece4119b20ee08f8c

**Comment by gewaechshaus** [comment]
@JSchlarb - are you using custom minification like @sydekumf wrote above?

**Comment by JSchlarb** [comment]
Nope
* magento 2.1.5 CE && EE
* PageDesigner (composer)
* modus prod
* cache disabled
* minifying enabled

**Comment by gewaechshaus** [comment]
- bundling and merging also enabled?
- Ubuntu 16.04.2 LTS
- Haproxy -> Varnish -> Nginx -> php-fpm with hhvm fallback

In my case cache is enabled and a bunch of modules are installed...

If you open up any layout element with a wysiwyg editor element inside, are the css classes still missing like in my case if you wanna edit the content in the modal by clicking on "wysiwyg" button?

 ![Image](https://pictr.com/images/2017/03/24/0e02b01d2b6cb52463ce371845f2fc92.jpg)
